# Generated by Django 5.1.1 on 2026-03-15 02:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='主キー')),
                ('visitor_name', models.CharField(max_length=100, verbose_name='来訪者')),
                ('visit_purpose', models.CharField(max_length=255, verbose_name='来訪目的')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('email', models.CharField(blank=True, max_length=255, null=True, verbose_name='メールアドレス')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='更新日時')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='論理削除')),
            ],
            options={
                'verbose_name': '来訪者',
                'verbose_name_plural': '来訪者一覧',
                'db_table': 'visitors',
            },
        ),
    ]
