# Generated by Django 6.0.3 on 2026-03-28 11:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='checked_in_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='受付日時'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_name',
            field=models.CharField(max_length=100, verbose_name='来訪者名'),
        ),
    ]
