# Generated by Django 6.0.3 on 2026-08-18 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0002_visitor_checked_in_at_alter_visitor_visitor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='組織名'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(message='メールアドレスは半角文字のみ入力できます。', regex='^[\\x20-\\x7E]*$')], verbose_name='メールアドレス'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='電話番号は半角数字とハイフン（-）のみ入力できます。', regex='^[0-9\\-]*$')], verbose_name='電話番号'),
        ),
    ]
